[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yoto-checkov"
version = "1.0.0"
description = "A publicly available collection of checkov tests used for AWS and the Serverless framework"
readme = "README.md"
requires-python = ">=3.8"

[tool.semantic_release]
version_variable = [
    "pyproject.toml:project.version"
]
build_command = "pytest"
changelog_file = "CHANGELOG.md"
upload_to_vcs_release = false

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"] 